### ISSUE TITLE
As a church member I want to login with my username and password

### ISSUE THREAD

**Issue by KyebagonzaJonathanJeremiah** [kanzucode/angie-server#22]
Once a church member is registered on the platform, they are free to login with their corresponding details. This distinguishes them from the visitors.

**Comment by lytes20** [comment]
Hey @KyebagonzaJonathanJeremiah thank you for creating this issue, could you just break down how you plan to implement this

**Comment by KyebagonzaJonathanJeremiah** [comment]
- [ ] Capture username
- [ ] Capture password
- [ ] Retrieve user details from database
- [ ] Validate if given details match with those in database
If they match;
- [ ] Authenticate login
- [ ] Return Login successful
- [ ] Else Username or password is incorrect
